{
    "language": "sl",
    "messages": [
        {
            "id": "The log file with directory: '{Directory}' failed to initialize",
            "message": "The log file with directory: '{Directory}' failed to initialize",
            "translation": "Napaka pri vzpostavitvi datoteke dnevnika v imeniku '{Directory}'",
            "placeholders": [
                {
                    "id": "Directory",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "directory"
                }
            ]
        },
        {
            "id": "The current server was not found when getting the VPN expiration date",
            "message": "The current server was not found when getting the VPN expiration date",
            "translation": ""
        },
        {
            "id": "The institute access server with URL: '{Identifier}' could not be added",
            "message": "The institute access server with URL: '{Identifier}' could not be added",
            "translation": "Strežnika z naslovom '{Identifier}' za dostop do ustanove ni bilo možno dodati",
            "placeholders": [
                {
                    "id": "Identifier",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "identifier"
                }
            ]
        },
        {
            "id": "The secure internet server with organisation ID: '{Identifier}' could not be added",
            "message": "The secure internet server with organisation ID: '{Identifier}' could not be added",
            "translation": "Strežnika za varni splet organizacije z ID-jem '{Identifier}' ni bilo možno dodati",
            "placeholders": [
                {
                    "id": "Identifier",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "identifier"
                }
            ]
        },
        {
            "id": "The custom server with URL: '{Identifier}' could not be added",
            "message": "The custom server with URL: '{Identifier}' could not be added",
            "translation": "Svojega strežnika z naslovom '{Identifier}' ni bilo možno dodati",
            "placeholders": [
                {
                    "id": "Identifier",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "identifier"
                }
            ]
        },
        {
            "id": "input: '{Identifier}' is not a valid URL",
            "message": "input: '{Identifier}' is not a valid URL",
            "translation": "",
            "placeholders": [
                {
                    "id": "Identifier",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "identifier"
                }
            ]
        },
        {
            "id": "Server identifier: '{Identifier}', is not valid when getting a VPN configuration",
            "message": "Server identifier: '{Identifier}', is not valid when getting a VPN configuration",
            "translation": "",
            "placeholders": [
                {
                    "id": "Identifier",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "identifier"
                }
            ]
        },
        {
            "id": "The client tried to autoconnect to the VPN server: '{Identifier}', but you need to authorizate again. Please manually connect again",
            "message": "The client tried to autoconnect to the VPN server: '{Identifier}', but you need to authorizate again. Please manually connect again",
            "translation": "",
            "placeholders": [
                {
                    "id": "Identifier",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "identifier"
                }
            ]
        },
        {
            "id": "The client tried to autoconnect to the VPN server: '{Identifier}', but the operation failed to complete",
            "message": "The client tried to autoconnect to the VPN server: '{Identifier}', but the operation failed to complete",
            "translation": "",
            "placeholders": [
                {
                    "id": "Identifier",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "identifier"
                }
            ]
        },
        {
            "id": "Server: '{Identifier}' could not be obtained",
            "message": "Server: '{Identifier}' could not be obtained",
            "translation": "",
            "placeholders": [
                {
                    "id": "Identifier",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "identifier"
                }
            ]
        },
        {
            "id": "No VPN configuration for server: '{Identifier}' could be obtained",
            "message": "No VPN configuration for server: '{Identifier}' could be obtained",
            "translation": "",
            "placeholders": [
                {
                    "id": "Identifier",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "identifier"
                }
            ]
        },
        {
            "id": "Server identifier: '{Identifier}', is not valid when removing the server",
            "message": "Server identifier: '{Identifier}', is not valid when removing the server",
            "translation": "",
            "placeholders": [
                {
                    "id": "Identifier",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "identifier"
                }
            ]
        },
        {
            "id": "The server: '{Identifier}' could not be removed",
            "message": "The server: '{Identifier}' could not be removed",
            "translation": "",
            "placeholders": [
                {
                    "id": "Identifier",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "identifier"
                }
            ]
        },
        {
            "id": "The current server could not be retrieved",
            "message": "The current server could not be retrieved",
            "translation": ""
        },
        {
            "id": "Failed to set the profile ID: '{PID}'",
            "message": "Failed to set the profile ID: '{PID}'",
            "translation": "",
            "placeholders": [
                {
                    "id": "PID",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "pID"
                }
            ]
        },
        {
            "id": "The current server was not found when cleaning up the connection",
            "message": "The current server was not found when cleaning up the connection",
            "translation": ""
        },
        {
            "id": "No OAuth tokens were found when cleaning up the connection",
            "message": "No OAuth tokens were found when cleaning up the connection",
            "translation": ""
        },
        {
            "id": "The server was unable to be retrieved when cleaning up the connection",
            "message": "The server was unable to be retrieved when cleaning up the connection",
            "translation": ""
        },
        {
            "id": "Failed to cleanup the VPN connection",
            "message": "Failed to cleanup the VPN connection",
            "translation": ""
        },
        {
            "id": "Failed to get the secure internet server with id: '{OrgID}' for setting a location",
            "message": "Failed to get the secure internet server with id: '{OrgID}' for setting a location",
            "translation": "",
            "placeholders": [
                {
                    "id": "OrgID",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "orgID"
                }
            ]
        },
        {
            "id": "The current server could not be retrieved when renewing the session",
            "message": "The current server could not be retrieved when renewing the session",
            "translation": ""
        },
        {
            "id": "The server was unable to be retrieved when renewing the session",
            "message": "The server was unable to be retrieved when renewing the session",
            "translation": ""
        },
        {
            "id": "Failover failed to complete with gateway: '{Gateway}' and MTU: '{Mtu}'",
            "message": "Failover failed to complete with gateway: '{Gateway}' and MTU: '{Mtu}'",
            "translation": "Preklop ni uspel s prehodom '{Gateway}' in MTU-jem '{Mtu}'",
            "placeholders": [
                {
                    "id": "Gateway",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "gateway"
                },
                {
                    "id": "Mtu",
                    "string": "%[2]d",
                    "type": "int",
                    "underlyingType": "int",
                    "argNum": 2,
                    "expr": "mtu"
                }
            ]
        },
        {
            "id": "An error occurred after getting the discovery files for the list of organizations",
            "message": "An error occurred after getting the discovery files for the list of organizations",
            "translation": "Pri nalaganju datotek kataloga organizacij je prišlo do napake"
        },
        {
            "id": "An error occurred after getting the discovery files for the list of servers",
            "message": "An error occurred after getting the discovery files for the list of servers",
            "translation": "Pri nalaganju datotek kataloga strežnikov je prišlo do napake"
        },
        {
            "id": "The VPN proxy exited",
            "message": "The VPN proxy exited",
            "translation": ""
        },
        {
            "id": "timeout reached for URL: '{URL}' and HTTP method: '{Method}'",
            "message": "timeout reached for URL: '{URL}' and HTTP method: '{Method}'",
            "translation": "",
            "placeholders": [
                {
                    "id": "URL",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "tErr.URL"
                },
                {
                    "id": "Method",
                    "string": "%[2]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 2,
                    "expr": "tErr.Method"
                }
            ]
        },
        {
            "id": "with cause:",
            "message": "with cause:",
            "translation": "; razlog:"
        },
        {
            "id": "An internal error occurred",
            "message": "An internal error occurred",
            "translation": "Prišlo je do notranje napake"
        }
    ]
}